### PR TITLE
Swift3.0

### PR DESCRIPTION
**Pull request by Econa77**
- Support Swift3.0
- Build Xcode8

### CODE REVIEW

**Comment by Econa77** [comment]
@takasek Could you review the code? 🚀

**Comment by takasek** [comment]
I'm sorry to be late responding.  I'm checking for now!

**Comment by takasek** [comment]
@Econa77 Thank you for the pull request!  It works fine.
But it seems better to use `Notification.Name` instead of `String`
Basing on your code, I added some trivial fixes on #6 and merge to master.

**Comment by Econa77** [comment]
Thanks @takasek 😄

**Pull request closed without merging**
